// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackToTop: typeof import('./src/components/backToTop.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLi: typeof import('element-plus/es')['ElLi']
    ElRow: typeof import('element-plus/es')['ElRow']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopNavBar: typeof import('./src/components/layout/TopNavBar.vue')['default']
    VArticleCard: typeof import('./src/components/v-articleCard.vue')['default']
    VAuthorCard: typeof import('./src/components/v-authorCard.vue')['default']
    VLogin: typeof import('./src/components/v-login.vue')['default']
  }
}
